#include <iostream>
#include <fstream>
#include "CodeGenerator.h"

using namespace std;

CodeGen::CodeGen (string filename)
{
	string pyname = filename.substr (0, filename.length()-3) + ".py"; 
	py.open (pyname.c_str());
	py << "# Autogenerated Scheme to Python Code\n";
	py << "# File: " << pyname << "\n";
	py << "from objectFunctionality import * \n\n";
	//cpp << "#include <iostream>\n";
	//cpp << "#include \"Object.h\"\n";
	//cpp << "using namespace std;\n\n";
}

/********************************************************************************/
/* This function will								*/
/********************************************************************************/
CodeGen::~CodeGen ()
{
	py.close();
}

/********************************************************************************/
/* This function will								*/
/********************************************************************************/
void CodeGen::WriteCode (int tabs, string code)
{
	for (int t = 0; t < tabs; t++)
		py << '\t';
	py << code;
}
