# Autogenerated Scheme to Python Code
# File: P3T3-1.py
from objectFunctionality import * 

def main(): 
	
	if (0):
		0
	else:
		123

	
	if 	123	
		" number? "

	if 	456	
		789

	
	(2+3)<(3-2)	
	(4/2)>(2*3)	
	(10%3)>=(4.234)	
	(4)<=(3)	
	func2	

def func2(): 
	
	print(	" 'list? zero? null? string? + ") 	
	print('')	

