# Autogenerated Scheme to Python Code
# File: P3T5.py
from objectFunctionality import * 

def square(n): 
	
	if 	n:
		n		*		n':
		"invalid_parameter"

	

def reciprocal(n): 
	
	if 	n	 and 	not 	n	==	0:
		1		/n':
		"invalid_parameter"

	

