# Autogenerated Scheme to Python Code
# File: P3T5.py
from objectFunctionality import * 

def square(n): 
	
	if numberp(n):
		n*n
	else:
		"invalid_parameter"

	

def reciprocal(n): 
	
	if numberp(n) and not (n)==(0):
		1/n
	else:
		"invalid_parameter"

	

