# Autogenerated Scheme to Python Code
# File: P3T6.py
from objectFunctionality import * 

def even_copy(ls): 
	
	if listp(ls):
		if nullp(ls)
			" "

		if nullp(cdr(ls) )
			" "

		else:
			cons(			car(			cdr(			ls) ) 			even_copy			cddr(			ls) )

':
		"even_copy_requires_a_list_argument"

	

def list_sum(ls): 
	
	if listp(ls):
		if nullp(ls):
			0(:
			if numberp(car(ls) ):
				car(				ls) +list_sumcdr(ls) (:
				0+list_sumcdr(ls) 



0:
		0

	

