# Autogenerated Scheme to Python Code
# File: P3T6.py
from objectFunctionality import * 

def even_copy(ls): 
	
	if 	ls:
		if 			ls			
			" "

			cdr(			ls) 			
			" "

			else:
				cons(				car(				cdr(				ls) ) 				even_copy				cddr(				ls) )

':
		"even_copy_requires_a_list_argument"

	

def list_sum(ls): 
	
	if 	ls:
		if 		ls:
			0(:
			if 			car(			ls) :
				car(				ls) 				+				list_sum				cdr(				ls) (:
				0				+				list_sum				cdr(				ls) 



0:
		0

	

