# Autogenerated Scheme to Python Code
# File: P3T6.py
from objectFunctionality import * 

def even_copy(ls): 
	
	if listp(ls):
		if nullp(ls)
			" "

		if nullp(listop(cdr,ls) )
			" "

		else:
			cons(			listop(car,listop(cdr,ls) ) 			even_copy			listop(cddr,ls) )


	else:
		"even_copy_requires_a_list_argument"

	

def list_sum(ls): 
	
	if listp(ls):
		if nullp(ls):
			0
		else:
			if numberp(listop(car,ls) ):
				listop(car,ls) +list_sumlistop(cdr,ls) 
			else:
				0+list_sumlistop(cdr,ls) 




	else:
		0

	

